// Code generated by "stringer -type=Language,Integration,Developmentkit,Crates"; DO NOT EDIT.

package interoperability_bridge_golang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LanguageJvm-1]
	_ = x[LanguageSwift-2]
	_ = x[LanguageNode-3]
	_ = x[LanguageBeam-4]
	_ = x[LanguageDart-5]
	_ = x[LanguageGolang-6]
	_ = x[LanguageRuby-7]
	_ = x[LanguagePython-8]
	_ = x[LanguageNet-9]
}

const _Language_name = "LanguageJvmLanguageSwiftLanguageNodeLanguageBeamLanguageDartLanguageGolangLanguageRubyLanguagePythonLanguageNet"

var _Language_index = [...]uint8{0, 11, 24, 36, 48, 60, 74, 86, 100, 111}

func (i Language) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Language_index)-1 {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[idx]:_Language_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IntegrationPending-1]
	_ = x[IntegrationCompleted-2]
}

const _Integration_name = "IntegrationPendingIntegrationCompleted"

var _Integration_index = [...]uint8{0, 18, 38}

func (i Integration) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Integration_index)-1 {
		return "Integration(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Integration_name[_Integration_index[idx]:_Integration_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DevelopmentkitCli-1]
	_ = x[DevelopmentkitApp-2]
}

const _Developmentkit_name = "DevelopmentkitCliDevelopmentkitApp"

var _Developmentkit_index = [...]uint8{0, 17, 34}

func (i Developmentkit) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Developmentkit_index)-1 {
		return "Developmentkit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Developmentkit_name[_Developmentkit_index[idx]:_Developmentkit_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CratesUniffi-1]
	_ = x[CratesWasm-2]
	_ = x[CratesNeon-3]
	_ = x[CratesRustler-4]
	_ = x[CratesRobusta-5]
	_ = x[CratesFrb-6]
	_ = x[CratesMagnus-7]
	_ = x[CratesPyo3-8]
	_ = x[CratesRnet-9]
}

const _Crates_name = "CratesUniffiCratesWasmCratesNeonCratesRustlerCratesRobustaCratesFrbCratesMagnusCratesPyo3CratesRnet"

var _Crates_index = [...]uint8{0, 12, 22, 32, 45, 58, 67, 79, 89, 99}

func (i Crates) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Crates_index)-1 {
		return "Crates(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Crates_name[_Crates_index[idx]:_Crates_index[idx+1]]
}
